imp: trying to test that the exceptions thrown by executions of asynchronous tasks have been logged. With the LogStub class, i got this scenario:
                record(LogLevel.DEBUG);
                recordLoggingForType(Countdown.class);
                // recordLoggingForType(ThorwUncheckedExceptionTask.class);
                // recordLoggingForType(LogExceptionAspect.class);
18:00:47.717 [main] DEBUG max.utility.tomato.Countdown - before timer
18:00:47.721 [main] DEBUG max.utility.tomato.Countdown - after timer
18:00:50.723 [pool-2-thread-1] DEBUG m.u.t.a.task.LogExceptionAspect - execution(public java.lang.Object max.utility.tomato.tasks.ThorwUncheckedExceptionTask.call())
18:00:50.723 [pool-2-thread-1] DEBUG m.u.t.t.ThorwUncheckedExceptionTask - call from ThorwUncheckedExceptionTask
18:00:50.727 [pool-2-thread-1] ERROR m.u.t.a.task.LogExceptionAspect - #catch_block#
java.lang.RuntimeException: bla bla bla
                            at max.utility.tomato.tasks.ThorwUncheckedExceptionTask.call_aroundBody0(ThorwUncheckedExceptionTask.java:16) [test-classes/:na]
                            at max.utility.tomato.tasks.ThorwUncheckedExceptionTask.call_aroundBody1$advice(ThorwUncheckedExceptionTask.java:20) [test-classes/:na]
                            at max.utility.tomato.tasks.ThorwUncheckedExceptionTask.call(ThorwUncheckedExceptionTask.java:1) [test-classes/:na]
                            at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [na:1.7.0_05]
                            at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_05]
                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_05]
                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_05]
                            at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_05]
                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_05]
                            at java.lang.Thread.run(Unknown Source) [na:1.7.0_05]
[[DEBUG] before timer, [DEBUG] after timer]

                record(LogLevel.DEBUG);
                recordLoggingForType(Countdown.class);
                recordLoggingForType(ThorwUncheckedExceptionTask.class);
                // recordLoggingForType(LogExceptionAspect.class);
18:01:16.464 [main] DEBUG max.utility.tomato.Countdown - before timer
18:01:16.469 [main] DEBUG max.utility.tomato.Countdown - after timer
18:01:19.469 [pool-2-thread-1] DEBUG m.u.t.t.ThorwUncheckedExceptionTask - call from ThorwUncheckedExceptionTask
[[DEBUG] before timer, [DEBUG] after timer, [DEBUG] call from ThorwUncheckedExceptionTask]

                record(LogLevel.DEBUG);
                recordLoggingForType(Countdown.class);
                // recordLoggingForType(ThorwUncheckedExceptionTask.class);
                recordLoggingForType(LogExceptionAspect.class);
18:02:09.462 [main] DEBUG max.utility.tomato.Countdown - before timer
18:02:09.466 [main] DEBUG max.utility.tomato.Countdown - after timer
[[DEBUG] before timer, [DEBUG] after timer]

                record(LogLevel.DEBUG);
                recordLoggingForType(Countdown.class);
                recordLoggingForType(ThorwUncheckedExceptionTask.class);
                recordLoggingForType(LogExceptionAspect.class);
18:02:50.184 [main] DEBUG max.utility.tomato.Countdown - before timer
18:02:50.188 [main] DEBUG max.utility.tomato.Countdown - after timer
18:02:53.188 [pool-2-thread-1] DEBUG m.u.t.t.ThorwUncheckedExceptionTask - call from ThorwUncheckedExceptionTask
[[DEBUG] before timer, [DEBUG] after timer, [DEBUG] call from ThorwUncheckedExceptionTask]

As you see, the aspect is not executed (weaved ?) if is uncommented one of this two :
                // recordLoggingForType(ThorwUncheckedExceptionTask.class);
                // recordLoggingForType(LogExceptionAspect.class);

Frameworks logging are not usefull at all:
nov 07, 2012 6:25:59 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
Informazioni: Loading XML bean definitions from class path resource [max/utility/tomato/CountdownTest-context.xml]
nov 07, 2012 6:25:59 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
Informazioni: Refreshing org.springframework.context.support.GenericApplicationContext@50b7ad1a: startup date [Wed Nov 07 18:25:59 CET 2012]; root of context hierarchy
nov 07, 2012 6:25:59 PM org.springframework.context.weaving.DefaultContextLoadTimeWeaver setBeanClassLoader
Informazioni: Found Spring's JVM agent for instrumentation
[AppClassLoader@24df39bc] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
nov 07, 2012 6:25:59 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
Informazioni: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@61e34259: defining beans [org.springframework.context.weaving.As\
pectJWeavingEnabler#0,loadTimeWeaver,org.springframework.aop.config.internalAutoProxyCreator,max.utility.tomato.aspects.task.LogExceptionAspect#0,org.springframework.context.annot\
ation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredA\
nnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor]; root of factory hierarchy
....

The cause of this behavior may be the @Rule annotation of junit ?

Running the test with:
 -verbose -javaagent:C:\Users\MAX\.m2\repository\org\springframework\org.springframework.instrument\3.0.5.RELEASE\org.springframework.instrument-3.0.5.RELEASE.jar

you will see that the lines below are not printed with the uncommented code.
[Loaded max.utility.tomato.aspects.task.LogExceptionAspect from __JVM_DefineClass__]
[Loaded max.utility.tomato.aspects.task.LogExceptionAspect from __JVM_DefineClass__]